# -*- coding: utf-8 -*-

#Created on  Jul 20 11:43:52 2016

#@author: Ankit Singh
Main:
    Input : '/home/ujjaldas223/projects/QRCodeReader/Input/'
    Output: '/home/ujjaldas223/projects/QRCodeReader/Results/'
FileType:
    - jpg
    - png
